version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=41120
      - ConnectionString=server=db;port=3306;database=jamins_db;user=root;password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/users.api.pfx 
    volumes:
      - ${HOME}/.aspnet/https:/https:rw
    networks:
      - user-network
    ports:
      - "30513:80"
      - "41120:443"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jamins_db
    networks:
      - user-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  db_data:

networks:
  user-network:
    driver: bridge