version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44311
      - ConnectionString=${CONNECTION_STRING}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./conf.d/https/dev_cert.pfx
    ports:
      - "30513:80"
      - "41120:443"
    volumes:
      - ./conf.d/https/:/https/
    networks:
      - user-network
    ports:
      - "30513:80"
      - "41120:443"
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password321
      MYSQL_DATABASE: jamins_db
    networks:
      - user-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  db_data:

networks:
  user-network: